export type SessionDuration = 10 | 20 | 30 | 60 | 120
export type TopicStatus = 'not_started' | 'in_progress' | 'completed'
export type QuestionType = 'pyq' | 'sourced' | 'practice' | 'ai_generated'
export type VerificationStatus = 'verified' | 'unverified' | 'generated'
export type AISessionType = 'explain' | 'teach' | 'summarize' | 'mcq' | 'viva' | 'answer' | 'page_explanation'
export type VivaDifficulty = 'basic' | 'intermediate' | 'advanced' | 'mixed'
export type VivaMode = 'rapid_fire' | 'standard' | 'examiner' | 'clinical'
export type ExaminerPersonality = 'friendly' | 'standard' | 'strict'
export type VivaMistakeType = 'did_not_know' | 'partially_correct' | 'incorrect' | 'incomplete' | 'concept_confusion' | 'poor_reasoning' | 'irrelevant' | 'correct'
export type Student = { id: string; name: string | null; course: string | null; year: string | number | null; university: string | null; academicYear: string | null }
export type Subject = { id: string; name: string; code: string | null; year: string | number | null; semester: string | number | null; progress: number; unitCount: number; topicCount: number }
export type Unit = { id: string; subjectId: string; name: string; order: number | null }
export type Topic = { id: string; subjectId: string; unitId: string | null; title: string; progress: number; status: TopicStatus }
export type Resource = { id: string; title: string; type: 'senior_notes' | 'textbook' | 'reference' | 'article'; author: string | null; edition: string | null; isbn: string | null; pageRange: string | null; url: string | null }
export type Question = { id: string; prompt: string; type: QuestionType; verification: VerificationStatus; source: string | null; subject: string | null; topic: string | null; institution: string | null; year: string | number | null; sourceBasis: string | null; importance: string | number | null }
export type Exam = { id: string; title: string; examDate: string; subjectId: string | null }
export type TimetableEntry = { id: string; title: string; day: string | null; date: string | null; startsAt: string | null; endsAt: string | null; location: string | null; entryType: string | null }
export type TopicProgress = { id: string; topicId: string; status: TopicStatus; completion: number }
export type QuestionAttempt = { id: string; questionId: string; isCorrect: boolean; attemptedAt: string }
export type StudySession = { id: string; durationMinutes: number; actualDurationMinutes: number | null; startedAt: string; completedAt: string | null }
export type AISession = { id: string; topicId: string; sessionType: AISessionType; createdAt: string }
export type AIMessage = { id: string; sessionId: string; role: 'user' | 'assistant'; content: string; createdAt: string }
export type StudentProfile = Pick<Student, 'name' | 'course' | 'year' | 'university' | 'academicYear'>
export type ProgressSummary = { overall: number; completedTopics: number; inProgressTopics: number; notStartedTopics: number; questionsAttempted: number; correctAnswers: number; studyMinutes: number }
export type QueryState<T> = { data: T; loading: boolean; error: string | null }
export type VivaQuestion = { id: string; prompt: string; topicId: string; topicTitle: string; difficulty: Exclude<VivaDifficulty, 'mixed'>; questionType: string; source: 'verified_question_bank' | 'practice_prompt' | 'ai_generated'; verification: VerificationStatus }
export type VivaEvaluation = { accuracy: number; completeness: number; reasoning: number; relevance: number; score: number; mistakeType: VivaMistakeType; feedback: string }
export type VivaAnswer = { questionId: string; topicId: string; answer: string; evaluation: VivaEvaluation }
export type VivaSessionRecord = { id: string; subjectId: string; subjectName: string; selectedUnitIds: string[]; selectedTopicIds: string[]; portionLabel: string; difficulty: VivaDifficulty; mode: VivaMode; personality: ExaminerPersonality; questionCount: number; startedAt: string; endedAt?: string; answers: VivaAnswer[]; score?: number }