import { useEffect, useState } from 'react'
import { BarChart3, CheckCircle2, Clock3, HelpCircle, ListChecks, MessageCircleQuestion } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState } from '../components/EmptyState'
import { QueryState } from '../components/QueryState'
import { getProgressSummary } from '../services/academic'
import { readVivaHistory, vivaModeLabel } from '../services/viva'
import type { ProgressSummary, VivaSessionRecord } from '../types'

const empty: ProgressSummary = { overall: 0, completedTopics: 0, inProgressTopics: 0, notStartedTopics: 0, questionsAttempted: 0, correctAnswers: 0, studyMinutes: 0 }
export function Progress() { const [state, setState] = useState({ loading: true, error: null as string | null, progress: empty, vivaHistory: [] as VivaSessionRecord[] }); useEffect(() => { let active = true; getProgressSummary().then((progress) => { if (active) setState({ loading: false, error: null, progress, vivaHistory: readVivaHistory() }) }).catch((error: unknown) => { if (active) setState({ loading: false, error: error instanceof Error ? error.message : 'Progress could not be loaded.', progress: empty, vivaHistory: readVivaHistory() }) }); return () => { active = false } }, []); const stats = [{ label: 'Overall progress', value: `${state.progress.overall}%`, icon: BarChart3 }, { label: 'Completed topics', value: String(state.progress.completedTopics), icon: CheckCircle2 }, { label: 'In-progress topics', value: String(state.progress.inProgressTopics), icon: Clock3 }, { label: 'Questions attempted', value: String(state.progress.questionsAttempted), icon: HelpCircle }, { label: 'Correct answers', value: String(state.progress.correctAnswers), icon: ListChecks }]; return <div className="page-stack"><section className="page-intro"><span className="eyebrow">Your record</span><h1>Progress & history</h1><p className="lede">A transparent view of what you have studied and practised so far.</p></section><QueryState loading={state.loading} error={state.error} isEmpty={false} emptyTitle="" emptyDescription=""><><div className="stats-grid">{stats.map(({ label, value, icon: Icon }) => <article className="stat-card" key={label}><Icon size={19} /><span className="eyebrow">{label}</span><strong>{value}</strong></article>)}</div><section className="card history-card"><div className="section-heading"><div><span className="eyebrow">Study time</span><h2>Study history</h2></div><span className="time-total"><Clock3 size={16} /> {state.progress.studyMinutes} min</span></div><EmptyState title="No study history yet" description="Complete a study session to see your activity here." /></section><section className="card viva-history-card"><div className="section-heading"><div><span className="eyebrow">Viva simulator</span><h2>Viva history</h2></div><MessageCircleQuestion size={19} /></div>{state.vivaHistory.length ? <div className="viva-history-list">{state.vivaHistory.map((record) => <Link className="viva-history-row" to={`/viva?sessionId=${record.id}`} key={record.id}><div><strong>{record.subjectName}</strong><span>{record.portionLabel}</span></div><div><span>{record.answers.length} questions · {vivaModeLabel(record.mode)}</span><strong>{record.score ?? 0}%</strong></div></Link>)}</div> : <EmptyState title="No viva history yet" description="Completed viva reports will appear here." />}</section></></QueryState></div> }
