import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CheckCircle2, ChevronDown, Circle, LockKeyhole, MessageCircleQuestion, RotateCcw, Send, ShieldCheck } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { QueryState } from '../components/QueryState'
import { getSubjectDetail, getSubjects, getVivaQuestionPool } from '../services/academic'
import { generateVivaQuestions } from '../services/ai'
import { evaluateAnswer, readVivaHistory, saveVivaSession, vivaModeLabel, type VivaConfig } from '../services/viva'
import type { ExaminerPersonality, Subject, Topic, Unit, VivaAnswer, VivaDifficulty, VivaMode, VivaQuestion, VivaSessionRecord } from '../types'
import '../viva.css'

type SubjectTree = { subject: Subject; units: Unit[]; topics: Topic[] }
const difficulties: VivaDifficulty[] = ['basic', 'intermediate', 'advanced', 'mixed']
const modes: VivaMode[] = ['rapid_fire', 'standard', 'examiner', 'clinical']
const personalities: ExaminerPersonality[] = ['friendly', 'standard', 'strict']
const counts = [5, 10, 15, 20]
function titleCase(value: string): string { return value.replace('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()) }

export function Viva() {
  const [searchParams] = useSearchParams(); const [trees, setTrees] = useState<SubjectTree[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [subjectId, setSubjectId] = useState(searchParams.get('subjectId') ?? ''); const [selectedUnits, setSelectedUnits] = useState<string[]>([]); const [selectedTopics, setSelectedTopics] = useState<string[]>([]); const [difficulty, setDifficulty] = useState<VivaDifficulty>('mixed'); const [mode, setMode] = useState<VivaMode>('standard'); const [personality, setPersonality] = useState<ExaminerPersonality>('standard'); const [questionCount, setQuestionCount] = useState(5); const [phase, setPhase] = useState<'setup' | 'active' | 'complete'>('setup'); const [questions, setQuestions] = useState<VivaQuestion[]>([]); const [questionIndex, setQuestionIndex] = useState(0); const [answer, setAnswer] = useState(''); const [answers, setAnswers] = useState<VivaAnswer[]>([]); const [lastEvaluation, setLastEvaluation] = useState<VivaAnswer | null>(null); const [session, setSession] = useState<VivaSessionRecord | null>(null); const [busy, setBusy] = useState(false)
  useEffect(() => { let active = true; getSubjects().then(async (subjects) => { const result = await Promise.all(subjects.map(async (subject) => { const detail = await getSubjectDetail(subject.id); return { subject: detail.subject ?? subject, units: detail.units, topics: detail.topics } })); if (active) { setTrees(result); if (!subjectId && result[0]) setSubjectId(result[0].subject.id); const saved = searchParams.get('sessionId') ? readVivaHistory().find((record) => record.id === searchParams.get('sessionId')) : null; if (saved) { setSession(saved); setAnswers(saved.answers); setPhase('complete') } setLoading(false) } }).catch((requestError: unknown) => { if (active) { setError(requestError instanceof Error ? requestError.message : 'Viva portions could not be loaded.'); setLoading(false) } }); return () => { active = false } }, [searchParams, subjectId])
  // The curriculum arrives asynchronously, so this synchronizes URL selection after the tree is loaded.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { const topicId = searchParams.get('topicId'); if (!topicId || !trees.length) return; const matchingTree = trees.find((item) => item.topics.some((topic) => topic.id === topicId)); if (!matchingTree) return; const matchingTopic = matchingTree.topics.find((topic) => topic.id === topicId); if (matchingTree.subject.id !== subjectId) setSubjectId(matchingTree.subject.id); if (matchingTopic) { setSelectedTopics([matchingTopic.id]); setSelectedUnits(matchingTopic.unitId ? [matchingTopic.unitId] : []) } }, [searchParams, subjectId, trees])
  const tree = trees.find((item) => item.subject.id === subjectId) ?? null
  const selectedTopicRecords = useMemo(() => tree?.topics.filter((topic) => selectedTopics.includes(topic.id)) ?? [], [selectedTopics, tree])
  const currentQuestion = questions[questionIndex]
  const portionLabel = selectedTopicRecords.length === 1 ? selectedTopicRecords[0].title : `${tree?.subject.name ?? 'Subject'} · ${selectedTopicRecords.length} selected topics`
  const toggleUnit = (unit: Unit) => { const ids = tree?.topics.filter((topic) => topic.unitId === unit.id).map((topic) => topic.id) ?? []; const allSelected = ids.length > 0 && ids.every((id) => selectedTopics.includes(id)); setSelectedUnits((current) => allSelected ? current.filter((id) => id !== unit.id) : [...new Set([...current, unit.id])]); setSelectedTopics((current) => allSelected ? current.filter((id) => !ids.includes(id)) : [...new Set([...current, ...ids])]) }
  const toggleTopic = (topic: Topic) => { setSelectedTopics((current) => current.includes(topic.id) ? current.filter((id) => id !== topic.id) : [...current, topic.id]); const unitTopics = tree?.topics.filter((candidate) => candidate.unitId === topic.unitId) ?? []; setSelectedUnits((current) => topic.unitId && unitTopics.every((candidate) => selectedTopics.includes(candidate.id) || candidate.id === topic.id) ? [...new Set([...current, topic.unitId])] : current.filter((id) => id !== topic.unitId)) }
  async function startViva() { if (!tree || !selectedTopics.length) return; setBusy(true); setError(null); try { const config: VivaConfig = { subjectId: tree.subject.id, subjectName: tree.subject.name, selectedUnitIds: selectedUnits, selectedTopicIds: [...selectedTopics], portionLabel, difficulty, mode, personality, questionCount }; let pool: VivaQuestion[] = []; let aiError: unknown = null; try { pool = await generateVivaQuestions({ subjectId: tree.subject.id, selectedUnitIds: selectedUnits, selectedTopicIds: [...selectedTopics], selectedTopicContext: selectedTopicRecords.map((topic) => ({ id: topic.id, title: topic.title })), difficulty, mode, numberOfQuestions: questionCount }) } catch (requestError: unknown) { aiError = requestError } if (!pool.length) pool = await getVivaQuestionPool(selectedTopics); if (!pool.length) throw new Error(aiError instanceof Error ? `Gemini did not return questions: ${aiError.message}` : 'Gemini did not return questions. Deploy the latest generate-viva Edge Function and confirm GEMINI_API_KEY is configured.') ; const frozenQuestions = pool.filter((question) => selectedTopics.includes(question.topicId)).slice(0, questionCount); const record: VivaSessionRecord = { id: `viva-${Date.now()}`, ...config, startedAt: new Date().toISOString(), answers: [] }; setSession(record); setQuestions(frozenQuestions); setQuestionIndex(0); setAnswers([]); setLastEvaluation(null); setPhase('active') } catch (startError: unknown) { setError(startError instanceof Error ? startError.message : 'Viva could not be started.') } finally { setBusy(false) } }
  function submitAnswer(value = answer) { if (!currentQuestion || lastEvaluation) return; const evaluation = evaluateAnswer(value, currentQuestion, personality); const nextAnswer = { questionId: currentQuestion.id, topicId: currentQuestion.topicId, answer: value.trim() || "I don't know", evaluation }; setAnswers((current) => [...current, nextAnswer]); setLastEvaluation(nextAnswer); setAnswer('') }
  function nextQuestion() { if (!lastEvaluation) return; if (questionIndex + 1 >= questions.length) { const completed = { ...session!, endedAt: new Date().toISOString(), answers: [...answers, lastEvaluation], score: Math.round(([...answers, lastEvaluation].reduce((sum, item) => sum + item.evaluation.score, 0) / Math.max(questions.length, 1)) * 10) }; setSession(completed); saveVivaSession(completed); setAnswers(completed.answers); setPhase('complete') } else { setQuestionIndex((current) => current + 1); setLastEvaluation(null) } }
  const reset = () => { setPhase('setup'); setQuestions([]); setQuestionIndex(0); setAnswers([]); setLastEvaluation(null); setSession(null) }
  return <div className="page-stack"><Link className="back-link" to="/subjects"><ArrowLeft size={16} /> Back to subjects</Link><section className="page-intro"><span className="eyebrow">Viva simulator</span><h1>{phase === 'active' ? 'Viva in progress.' : phase === 'complete' ? 'Viva complete.' : 'Choose your portion.'}</h1><p className="lede">Every question is locked to the topics you select. The examiner cannot expand the portion.</p></section><QueryState loading={loading} error={error} isEmpty={!trees.length} emptyTitle="No viva-ready curriculum" emptyDescription="Add subjects and topics before starting a portion-based viva.">{phase === 'setup' && <Setup tree={tree} trees={trees} subjectId={subjectId} setSubjectId={(id) => { setSubjectId(id); setSelectedUnits([]); setSelectedTopics([]) }} selectedUnits={selectedUnits} selectedTopics={selectedTopics} toggleUnit={toggleUnit} toggleTopic={toggleTopic} difficulty={difficulty} setDifficulty={setDifficulty} mode={mode} setMode={setMode} personality={personality} setPersonality={setPersonality} questionCount={questionCount} setQuestionCount={setQuestionCount} busy={busy} startViva={startViva} />}{phase === 'active' && currentQuestion && <ActiveViva session={session!} question={currentQuestion} index={questionIndex} total={questions.length} answer={answer} setAnswer={setAnswer} evaluation={lastEvaluation?.evaluation ?? null} submitAnswer={submitAnswer} nextQuestion={nextQuestion} />}{phase === 'complete' && session && <CompleteViva session={session} answers={answers} reset={reset} />}</QueryState></div>
}

type SetupProps = { tree: SubjectTree | null; trees: SubjectTree[]; subjectId: string; setSubjectId: (id: string) => void; selectedUnits: string[]; selectedTopics: string[]; toggleUnit: (unit: Unit) => void; toggleTopic: (topic: Topic) => void; difficulty: VivaDifficulty; setDifficulty: (value: VivaDifficulty) => void; mode: VivaMode; setMode: (value: VivaMode) => void; personality: ExaminerPersonality; setPersonality: (value: ExaminerPersonality) => void; questionCount: number; setQuestionCount: (value: number) => void; busy: boolean; startViva: () => void }
function Setup({ tree, trees, subjectId, setSubjectId, selectedUnits, selectedTopics, toggleUnit, toggleTopic, difficulty, setDifficulty, mode, setMode, personality, setPersonality, questionCount, setQuestionCount, busy, startViva }: SetupProps) { return <div className="viva-setup"><section className="viva-portion card"><div className="viva-section-heading"><div><span className="eyebrow">Step 1</span><h2>Select your portion</h2></div><LockKeyhole size={19} /></div><label className="select-label">Subject<select value={subjectId} onChange={(event) => setSubjectId(event.target.value)}>{trees.map((item) => <option value={item.subject.id} key={item.subject.id}>{item.subject.name}</option>)}</select></label><div className="viva-tree">{tree?.units.map((unit) => { const unitTopics = tree.topics.filter((topic) => topic.unitId === unit.id); return <div className="viva-unit" key={unit.id}><button className={`viva-check-row ${selectedUnits.includes(unit.id) ? 'viva-check-row--selected' : ''}`} onClick={() => toggleUnit(unit)}><span>{selectedUnits.includes(unit.id) ? <CheckCircle2 size={17} /> : <Circle size={17} />}</span><strong>{unit.name}</strong><small>{unitTopics.length} topics</small><ChevronDown size={16} /></button><div className="viva-topics">{unitTopics.map((topic) => <button className={`viva-topic-row ${selectedTopics.includes(topic.id) ? 'viva-topic-row--selected' : ''}`} onClick={() => toggleTopic(topic)} key={topic.id}><span>{selectedTopics.includes(topic.id) ? <CheckCircle2 size={15} /> : <Circle size={15} />}</span>{topic.title}<small>{topic.progress}%</small></button>)}</div></div> })}</div></section><section className="viva-settings card"><div className="viva-section-heading"><div><span className="eyebrow">Step 2</span><h2>Set the viva</h2></div><MessageCircleQuestion size={19} /></div><OptionGroup label="Number of questions" values={counts} value={questionCount} onChange={setQuestionCount} /><OptionGroup label="Difficulty" values={difficulties} value={difficulty} onChange={setDifficulty} /><OptionGroup label="Mode" values={modes} value={mode} onChange={setMode} /><OptionGroup label="Examiner personality" values={personalities} value={personality} onChange={setPersonality} /><button className="button button--primary button--full" disabled={!selectedTopics.length || busy} onClick={startViva}>{busy ? 'Preparing portion...' : 'Start Viva'} <ShieldCheck size={16} /></button>{selectedTopics.length > 0 && <p className="viva-lock-note">{selectedTopics.length} topic{selectedTopics.length === 1 ? '' : 's'} locked into this viva.</p>}</section></div> }
function OptionGroup<T extends string | number>({ label, values, value, onChange }: { label: string; values: T[]; value: T; onChange: (value: T) => void }) { return <fieldset className="option-group"><legend>{label}</legend><div>{values.map((item) => <button type="button" className={value === item ? 'option--selected' : ''} onClick={() => onChange(item)} key={String(item)}>{typeof item === 'string' ? titleCase(item) : item}</button>)}</div></fieldset> }
function ActiveViva({ session, question, index, total, answer, setAnswer, evaluation, submitAnswer, nextQuestion }: { session: VivaSessionRecord; question: VivaQuestion; index: number; total: number; answer: string; setAnswer: (value: string) => void; evaluation: VivaAnswer['evaluation'] | null; submitAnswer: (value?: string) => void; nextQuestion: () => void }) { return <section className="viva-active"><div className="viva-active__header"><div><span className="eyebrow">Viva simulator · {vivaModeLabel(session.mode)}</span><h2>{session.subjectName}</h2><p>Portion locked: {session.portionLabel}</p></div><span className="viva-progress">Question {index + 1} / {total}</span></div><div className="viva-progress-bar"><span style={{ width: `${((index + 1) / total) * 100}%` }} /></div><article className="question-card"><div className="question-card__meta"><span>{titleCase(question.difficulty)}</span><span>{question.source === 'verified_question_bank' ? 'Sourced question' : 'Practice prompt'}</span></div><h1>{question.prompt}</h1><span className="question-topic">Topic boundary: {question.topicTitle}</span><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Type your answer..." disabled={Boolean(evaluation)} rows={6} /><div className="answer-actions">{!evaluation ? <><button className="button button--primary" onClick={() => submitAnswer()}><Send size={16} /> Submit answer</button><button className="button button--quiet" onClick={() => submitAnswer("I don't know")}>I don't know</button></> : <button className="button button--dark" onClick={nextQuestion}>{index + 1 === total ? 'View report' : 'Next question'} <ChevronDown size={16} /></button>}</div></article>{evaluation && <Evaluation evaluation={evaluation} />}</section> }
function Evaluation({ evaluation }: { evaluation: VivaAnswer['evaluation'] }) { return <section className="evaluation-card"><div className="viva-section-heading"><div><span className="eyebrow">Your evaluation</span><h2>{evaluation.score}/10 · {titleCase(evaluation.mistakeType)}</h2></div><CheckCircle2 size={19} /></div><div className="evaluation-grid">{[['Accuracy', evaluation.accuracy], ['Completeness', evaluation.completeness], ['Reasoning', evaluation.reasoning], ['Relevance', evaluation.relevance]].map(([label, score]) => <div key={String(label)}><span>{label}</span><strong>{score}/10</strong></div>)}</div><p>{evaluation.feedback}</p></section> }
function CompleteViva({ session, answers, reset }: { session: VivaSessionRecord; answers: VivaAnswer[]; reset: () => void }) { const correct = answers.filter((answer) => answer.evaluation.mistakeType === 'correct').length; const partial = answers.filter((answer) => answer.evaluation.mistakeType === 'partially_correct').length; const weak = [...new Set(answers.filter((answer) => answer.evaluation.score < 6).map((answer) => answer.topicId))]; return <section className="viva-report card"><div className="viva-report__hero"><span className="eyebrow">Viva complete</span><h2>{session.portionLabel}</h2><p>{session.subjectName} · {answers.length} questions · {titleCase(session.difficulty)} · {vivaModeLabel(session.mode)}</p><strong>{session.score ?? 0}%</strong></div><div className="report-stats"><div><strong>{correct}</strong><span>Correct</span></div><div><strong>{partial}</strong><span>Partially correct</span></div><div><strong>{answers.length - correct - partial}</strong><span>Needs review</span></div></div><div className="report-section"><span className="eyebrow">Selected topics</span><div className="report-topics">{[...new Set(answers.map((answer) => answer.topicId))].map((topicId) => <span key={topicId}>{answers.find((answer) => answer.topicId === topicId)?.evaluation.score && answers.find((answer) => answer.topicId === topicId)!.evaluation.score >= 6 ? '✓' : '×'} {topicId}</span>)}</div></div>{weak.length > 0 && <div className="report-revision"><span className="eyebrow">Needs revision</span><p>{weak.length} selected topic{weak.length === 1 ? '' : 's'} had weak answers. Retry remains locked to this original portion.</p><button className="button button--dark" onClick={reset}><RotateCcw size={16} /> Retry weak questions</button></div>}<button className="button button--quiet" onClick={reset}>Start another viva</button></section> }
